/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class jp_ac_nitech_hello_HelloJNI */

#ifndef _Included_hook_sample_h_
#define _Included_hook_sample_h_
#ifdef __cplusplus
extern "C" {
#endif

#include <jni.h>
#include <stdio.h>
#include <dlfcn.h>
#include <android/log.h>
/*
 * Class:     jp_ac_nitech_hello_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jp_ac_nitech_hook_HookLoadJNIActivity_printJNI(JNIEnv *env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif
